In [1]:
import numpy as np

In [2]:
my_array = np.array([1, 2, 3])

print(my_array)

[1 2 3]


In [3]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [5]:
my_array[0]

1

In [6]:
my_2d_array[1, 1]

5

In [7]:
import pandas as pd

In [8]:
instructors_data = {
    "name": ["Jamie", "Colin", "Neringa"],
    "fav_number": [7, 12, 4],
    index = [1, 2, 3]
}

instructors_data

{'name': ['Jamie', 'Colin', 'Neringa'], 'fav_number': [7, 12, 4]}

In [9]:
instructors_df = pd.DataFrame(instructors_data)

In [10]:
instructors_df

name  fav_number
0    Jamie           7
1    Colin          12
2  Neringa           4

In [11]:
type(instructors_df)

pandas.core.frame.DataFrame

In [16]:
instructors_data = pd.DataFrame({
    "name": ["Jamie", "Colin", "Neringa"],
    "fav_number": [7, 12, 4]},
    index = [1, 2, 3]
)

instructors_data

name  fav_number
1    Jamie           7
2    Colin          12
3  Neringa           4